### ISSUE TITLE
Cant open EPIX camera - pxd_PIXCIopen

### ISSUE THREAD

**Issue by pankajkgupta** [manoharan-lab/camera-controller#15]
I am using Win7 x64 to read frames from EPIX.
The XCAP can read the frames from camera and display fine.

I am trying to use this library to read frames in python3.7. 
The following call is returning error codes.
`self.epix.pxd_PIXCIopen("","", formatfile)`

I tried specifying several formatfile but all of them are returning -13 (Cant read the file or format not readable).

Does anyone have any idea what might be causing this?

**Comment by RebeccaWPerry** [comment]
What camera is connected through your PIXCI frame grabber? Also, looking at epix_framegrabber.py line 71, error -13 is can't find format file. Did you generate a format file matching the desired camera, bit depth, and pixel-wise dimensions and put it in the formatFiles directory? I haven't looked at this in years, but if I remember correctly, you can generate and export the format files in XCAP.

**Comment by pankajkgupta** [comment]
Hi, thanks for your reply.
I am using dalsa pantera 1M60 camera. 

I figured out the problem. The issue was with the string encoding of the parameters to XCLIB library.
Python encodes strings in unicode but the XCLIB library expects in ASCII.

This is how the working code looks
`formatfile = os.path.join("C:\\", "Users", "User", "Downloads", "camera-controller-master", "formatFiles", "xcvidset.fmt")`
`pxd_PIXCIopen("", "", formatfile.encode('utf-8'))`
